//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_UserFollow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam_UserFollow()
        {
            this.Result = new HashSet<Result>();
        }
    
        public string ID_ExamUser { get; set; }
        public string ID_Exam { get; set; }
        public string Estado_ExamUser { get; set; }
        public string Code_User { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result { get; set; }
    }
}
